### ISSUE TITLE
Calendar component - Initialization bug

### ISSUE THREAD

**Issue by lperamo** [lperamo/ecocomposer#1]
**Description**
When the calendar component is launched, there is a bug reported by the development console as follows :
> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentElement')
    at Object.init (calendar.ts:1110:96)
    at HTMLDocument._init (calendar.ts:10:26)

**Expected behavior**
No error in console when we launch the demo page.

**Desktop**
Tested on Ubuntu 22.04.1 LTS, Chromium "Version 109.0.5414.74 (Build officiel) snap (64 bits)"

**Comment by lperamo** [comment]
Same issue as #3
